import fs from 'node:fs';
import { MANIFEST_FILE } from './paths.mjs';

/**
 * Runtime manifest (assets/images/manifest.js) — a plain script that sets
 * window.SF_MANIFEST, so it also works when index.html is opened from disk.
 *
 * assets[id] = { src: 'assets/images/<generated|standin>/<cat>/<id>', w, h, source }
 * videos[id] = { webm, mp4, webmSm, mp4Sm, poster, credit }
 */
export function readManifest() {
  if (!fs.existsSync(MANIFEST_FILE)) return { assets: {}, videos: {} };
  const txt = fs.readFileSync(MANIFEST_FILE, 'utf8');
  const json = txt.slice(txt.indexOf('{'), txt.lastIndexOf('}') + 1);
  const data = JSON.parse(json);
  return { assets: data.assets || {}, videos: data.videos || {} };
}

export function writeManifest(m) {
  const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
  const data = { assets: sorted(m.assets), videos: sorted(m.videos) };
  const body =
    '/* Generated by tools/*.mjs — do not edit by hand. */\n' +
    `window.SF_MANIFEST = ${JSON.stringify(data, null, 1)};\n`;
  fs.mkdirSync(MANIFEST_FILE.replace(/[^/]+$/, ''), { recursive: true });
  fs.writeFileSync(MANIFEST_FILE, body);
}

/** Photographs (source 'hf') always win over stand-ins. */
export function setAsset(m, id, entry) {
  const prev = m.assets[id];
  if (prev && prev.source === 'hf' && entry.source !== 'hf') return false;
  m.assets[id] = entry;
  return true;
}
